services:
  - type: web
    name: stepup-sneakers
    runtime: php
    plan: free
    buildCommand: ""
    startCommand: apache2-foreground
    envVars:
      - key: DOCUMENT_ROOT
        value: nova
